[package]
name = "tanglearb-bot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tanglearb-bot"
path = "src/main.rs"

[dependencies]
iota-sdk = { version = "1.0" }
tokio = { version = "1", features = ["full"] }
rand = "0.8"
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"

